fsi_admin_security_password_reset_request:
    path: /password-reset/request
    defaults:
        _controller: admin_security.controller.password_reset.request:requestAction

fsi_admin_security_password_reset_change_password:
    path: /password-reset/{token}
    defaults:
        _controller: admin_security.controller.password_reset.change_password:changePasswordAction
